### ISSUE TITLE
Reference attribute in abac rules

### ISSUE THREAD

**Issue by Kern046** [Kilix/php-abac#33]
The goal is to turn this configuration : 

```yaml
    troop_leadership:
        attributes:
            user.isActive:
                comparison_type: boolean
                comparison: boolAnd
                value: true
            user.troopAssociations:
                comparison_type: array
                comparison: contains
                with:
                    troopAssociation.troop.id:
                        comparison_type: numeric
                        comparison: isEqual
                        value: dynamic
                    troopAssociation.role.position:
                        comparison_type: numeric
                        comparison: isEqual
                        value: 1
```

```php
if($this->get('kilix_abac.security')->enforce('troop_membership', $this->getUser(), $troop, [
    'dynamic_attributes' => ['troop-id' => $troop->getId()]
]) !== true) {
    throw new AccessDeniedHttpException('troops.access_denied');
}
```
to : 
```yaml
    troop_leadership:
        attributes:
            user.isActive:
                comparison_type: boolean
                comparison: boolAnd
                value: true
            user.troopAssociations:
                comparison_type: array
                comparison: contains
                with:
                    troopAssociation.troop.id:
                        comparison_type: object
                        comparison: isFieldEqual
                        value: id
                    troopAssociation.role.position:
                        comparison_type: numeric
                        comparison: isEqual
                        value: 1
```

```php
if($this->get('kilix_abac.security')->enforce('troop_membership', $this->getUser(), $troop) !== true) {
    throw new AccessDeniedHttpException('troops.access_denied');
}
```
